### ISSUE TITLE
Support DAVx5.

### ISSUE THREAD

**Issue by beedell-roke** [super-productivity/super-productivity#2719]
### A Description Of The Problem

I don't want to have to duplicate account configuration across applications, so this would mitigate [`issues/2718`](https://github.com/super-productivity/super-productivity/issues/2718#issue-1848231183), by providing a subset, in a manner that is interoperable with other applications.

### Potential Solutions

Support consuming accounts added via [`bitfireAT/davx5-ose` (see `e6125dd6440d47239a577d0cab9a62f0a7dab952/README.md#davx`)](https://github.com/bitfireAT/davx5-ose/blob/e6125dd6440d47239a577d0cab9a62f0a7dab952/README.md#davx).

### Potential Alternatives

What currently occurs — adding the accounts via each (this) application.

### Additional Context

This affects ⪆ [`davx5-ose/releases/tag/v4.4.2-ose`](https://github.com/bitfireAT/davx5-ose/releases/tag/v4.4.2-ose).

**Comment by RokeJulianLockhart** [comment]
> https://github.com/johannesjo/super-productivity/issues/2719#issuecomment-1859010600

https://github.com/johannesjo/super-productivity/issues/2717#issuecomment-1859015746

**Comment by RokeJulianLockhart** [comment]
> https://github.com/johannesjo/super-productivity/issues/2719#issuecomment-2060192020

@GitHub-Actions, https://github.com/johannesjo/super-productivity/issues/2717#issuecomment-1859015746

**Comment by sunjam** [comment]
Davx5 is the common open source Android app for using webdav, caldav and cardav.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/johannesjo/super-productivity/issues/2719#issuecomment-2292589413

@GitHub-Actions, https://github.com/johannesjo/super-productivity/issues/2717#issuecomment-1859015746

**Comment by culinia** [comment]
I would appreciate that feature very much, too

**Comment by johannesjo** [comment]
@everybody if you want to see this feature, you should ideally upvote the original issue. Thank you!

**Comment by RokeJulianLockhart** [comment]
> https://github.com/johannesjo/super-productivity/issues/2719#issuecomment-2599465896

@GitHub-Actions, it remains relevant.

**Comment by beedell-roke** [comment]
> [`#issuecomment-3424390494`](https://github.com/johannesjo/super-productivity/issues/2719#issuecomment-3424390494)

It remains relevant.

**Comment by johannesjo** [comment]
What is the expected scope for this? What should be synced? Are we just talking about the caldav integration or would you expect more than that?

**Comment by beedell-roke** [comment]
@johannesjo, DAVx<sup>5</sup> supports CalDAV `VJOURNAL`, `VTODO`, and `VEVENT`. Consdering that SP appears to solely support `VTODO` (as is expected), I solely want SP to be able to consume `VTODO`s from accounts that have been added via DAVx<sup>5</sup> (NextCloud being an example), and expose any accounts, added via SP, via DAVx<sup>5</sup>.

To summarise, if existent functionality can be replicated 1:1 via DAVx<sup>5</sup>, please route it via it. It practically replaces `com.android.settings.Settings$AccountDashboardActivity` for CalDAV.

**Comment by johannesjo** [comment]
This is how the technical specification might look like. Tbh I think it is quite a lot of effort and technical debt for something I'd consider more of a niche use case.



# Implementation Plan: DAVx⁵ Integration for CalDAV (Issue #2719)

## Overview
Add Android-only integration with DAVx⁵ (CalDAV/WebDAV account manager app) to help users set up CalDAV credentials without manual duplication. This is a Phase 1 implementation (Intent-based helper) that launches DAVx⁵ when users configure CalDAV providers.

**Key Points:**
- Android-only feature (hidden on Web/iOS/Electron)
- 100% backwards compatible (purely additive)
- Simple Intent-based approach (no permissions needed)
- Users still manually copy credentials, but DAVx⁵ makes it easier

## Files to Create

### 1. Android Plugin
**File:** `android/app/src/main/java/com/superproductivity/superproductivity/plugins/DavAccountPlugin.kt`

**Purpose:** Capacitor plugin providing native Android bridge to DAVx⁵

**Methods:**
- `isDavx5Installed()` - Check if DAVx⁵ app is installed
- `openDavx5LoginScreen(url?: string)` - Launch DAVx⁵ account setup screen via Intent

**Key Details:**
- Package: `at.bitfire.davdroid`
- Activity: `at.bitfire.davdroid.ui.setup.LoginActivity`
- Error handling for DAVx⁵ not installed

### 2. TypeScript Service
**File:** `src/app/features/issue/providers/caldav/dav-account-bridge.service.ts`

**Purpose:** Angular service wrapping the Capacitor plugin with web fallback

**Methods:**
- `checkDavx5Availability()` - Returns false on non-Android or when DAVx⁵ not installed
- `openDavx5Setup(serverUrl?: string)` - Launches DAVx⁵ or throws error

**Key Details:**
- Uses `registerPlugin` with web fallback that returns false/throws errors
- Checks `IS_ANDROID_WEB_VIEW` before calling native code
- Injectable with `providedIn: 'root'`

### 3. Unit Tests
**File:** `src/app/features/issue/providers/caldav/dav-account-bridge.service.spec.ts`

**Purpose:** Test service behavior on web platform (default test environment)

**Tests:**
- Service creation
- `checkDavx5Availability()` returns false on web
- `openDavx5Setup()` throws error on web

## Files to Modify

### 4. CalDAV Configuration Form
**File:** `src/app/features/issue/providers/caldav/caldav-cfg-form.const.ts`

**Changes:**
1. Import `IS_ANDROID_WEB_VIEW`, `DavAccountBridgeService`, `SnackService`, `inject`
2. Add `DAVX5_HELPER_FIELDS` constant (array of Formly fields):
   - Info text explaining DAVx⁵ integration
   - Button to launch DAVx⁵ (only shown when installed)
   - Link to install DAVx⁵ from F-Droid (only shown when NOT installed)
   - Help text for after viewing DAVx⁵ account
3. Spread `DAVX5_HELPER_FIELDS` at the beginning of `CALDAV_CONFIG_FORM`

**Field Logic:**
- On Android: Check DAVx⁵ availability in `onInit` hook, store in `model._isDavx5Available`
- Button `onClick`: Check availability → Launch DAVx⁵ → Show error snackbar if fails
- `hideExpression` on fields based on `_isDavx5Available` flag
- On non-Android: `DAVX5_HELPER_FIELDS` is empty array (no UI changes)

## Implementation Steps

1. ✅ Create `DavAccountPlugin.kt` with Intent-based methods
2. ✅ Create `dav-account-bridge.service.ts` with platform detection
3. ✅ Create `dav-account-bridge.service.spec.ts` with web platform tests
4. ✅ Update `caldav-cfg-form.const.ts` with DAVx⁵ helper fields
5. Run `npm run checkFile` on TypeScript files
6. Test on Android with DAVx⁵ installed (manual test)
7. Test on Android without DAVx⁵ (manual test)
8. Test on Web/Electron (ensure no UI changes)

## User Flow (Android with DAVx⁵ Installed)

1. User opens Super Productivity → Settings → Issue Providers
2. User clicks "Add CalDAV Provider"
3. User sees info text about DAVx⁵ integration
4. User clicks "Open DAVx⁵ to View/Add Account" button
5. DAVx⁵ app launches, showing account list/setup screen
6. User views existing CalDAV account or adds new one
7. User copies CalDAV URL from DAVx⁵
8. User creates app-specific password (recommended)
9. User returns to Super Productivity
10. User pastes URL, username, password into form fields
11. User saves and tests connection

## User Flow (Android without DAVx⁵)

1. Same as above but sees "Install DAVx⁵ from F-Droid" link instead of button
2. Can click link to install DAVx⁵
3. Can still enter credentials manually (existing behavior)

## User Flow (Non-Android Platforms)

1. No DAVx⁵ UI appears (form looks identical to current version)
2. Manual credential entry works as before

## Verification Steps

### Unit Tests
```bash
npm test -- --include='**/dav-account-bridge.service.spec.ts'
```

### Linting
```bash
npm run checkFile src/app/features/issue/providers/caldav/dav-account-bridge.service.ts
npm run checkFile src/app/features/issue/providers/caldav/caldav-cfg-form.const.ts
npm run checkFile src/app/features/issue/providers/caldav/dav-account-bridge.service.spec.ts
```

### Manual Testing (Android with DAVx⁵)
1. Build Android APK: `npm run dist:android`
2. Install on device/emulator with DAVx⁵ installed
3. Open CalDAV provider config
4. Verify "Open DAVx⁵" button appears
5. Click button → DAVx⁵ launches
6. Copy credentials from DAVx⁵
7. Paste into Super Productivity
8. Test connection succeeds

### Manual Testing (Android without DAVx⁵)
1. Uninstall DAVx⁵ from test device
2. Open CalDAV provider config
3. Verify "Install DAVx⁵" link appears (no button)
4. Verify manual entry still works

### Manual Testing (Web/Electron)
1. Open CalDAV provider config in browser or Electron
2. Verify NO DAVx⁵ button or install link appears
3. Form looks identical to current version
4. Manual CalDAV setup works

### Backwards Compatibility
1. Test existing CalDAV configurations still work
2. Sync tasks from CalDAV
3. No regressions in CalDAV functionality

## Success Criteria

- [ ] Android users can launch DAVx⁵ from CalDAV config screen
- [ ] Graceful handling when DAVx⁵ not installed (show install link)
- [ ] No UI changes on non-Android platforms
- [ ] All unit tests pass
- [ ] No linting errors
- [ ] CalDAV sync continues to work with credentials from any source
- [ ] Backwards compatible with existing configs

## Notes

- This is Phase 1 (Intent-based helper) - Phase 2 (AccountManager direct integration) could be added later
- No Android permissions required for Intent-based approach
- DAVx⁵ may or may not honor the `url` extra passed to Intent (best-effort)
- Translation keys marked as TODO for later i18n work
- Feature is additive only - no breaking changes
